export const GET_JOBS = 'GET_JOBS'
export const GET_FULL_TIME = 'GET_FULL_TIME'
export const SEARCH_JOBS = 'SEARCH_JOBS'
export const GET_LOCATION = 'GET_LOCATION'
export const GET_JOB = 'GET_JOB'
export const SET_LOADING = 'SET_LOADING'
